### ISSUE TITLE
BUG: host bits set

### ISSUE THREAD

**Issue by bitnol** [iv-org/smart-ipv6-rotator#12]
OS: Debian 12
Executed as root.

Debug info:

[INFO] You have IPv6 connectivity. Continuing.
[INFO] No cleanup of previous setup needed.
Traceback (most recent call last):
  File "/home/smart-ipv6-rotator/smart-ipv6-rotator.py", line 310, in <module>
    SmartIPv6Rotator()
  File "/home/smart-ipv6-rotator/smart-ipv6-rotator.py", line 53, in __init__
    getattr(self, args.command)()
  File "/home/smart-ipv6-rotator/smart-ipv6-rotator.py", line 183, in run
    ipv6_network = IPv6Network(args.ipv6range)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 2227, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: xxxx:xxxx:xxx:xx:xxxx:xxxx:xxxx:1/112 has host bits set

**Comment by bitnol** [comment]
I was able to fix it by changing the code in smart-ipv6-rotator.py line no 183

`ipv6_network = IPv6Network(args.ipv6range)`
to
`ipv6_network = IPv6Network(args.ipv6range, False)`

Hope this helps.

**Comment by unixfox** [comment]
Can you paste the args that you passed to the script?

You are not supposed to pass the "host" bit of the ipv6 address. But only the ipv6 range like specified in the example.

**Comment by bitnol** [comment]
Below was the command:
`python3 /home/smart-ipv6-rotator/smart-ipv6-rotator.py run --ipv6range=xxxx:xxx:xxx:xx:xxxx:xxxx:xxxx:0001/112`

**Comment by unixfox** [comment]
That's what I thought. Don't include the host bits.

Make sure to calculate the ipv6 range using this tool: http://www.gestioip.net/cgi-bin/subnet_calculator.cgi
