### ISSUE TITLE
script often fails with error

### ISSUE THREAD

**Issue by cfdisk** [iv-org/smart-ipv6-rotator#13]
Hi. Script often fails for me: 
```
[INFO] You have IPv6 connectivity. Continuing.
[INFO] Finished cleaning up previous setup.
[INFO] Waiting for the propagation in the Linux kernel.
[DEBUG] Debug info:
random_ipv6_address --> XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX 
random_ipv6_address_mask --> 64
gateway --> fe80::1
interface_index --> 2
interface_name --> eth0
ipv6_subnet --> XXXX:XXXX:XXXX:XXXX::/64
[Error] Failed to remove the configured (Google) IPv6 subnets.
        May be expected if the route were not yet configured and that was a cleanup due to an error.
[INFO] Finished cleaning up previous setup.
[INFO] Waiting for the propagation in the Linux kernel.
[ERROR] Failed to send the request for checking the new IPv6 address! The setup did not work!
        Your provider probably does not allow setting any arbitrary IPv6 address.
        Or did you correctly configured the IPv6 subnet to use?
       Exception:
HTTPConnectionPool(host='2606:4700::6812:7261', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe489f6b010>, 'Connection to 2606:4700::6812:7261 timed out. (connect timeout=5)'))
```
However, sometimes (rarely) it works without errors. New IP+route is then listed ( `ip a` and ` ip r` )
I have not yet been able to determine any regularity. 

Machine is a root server at netcup. 

EDIT: 
Debian12.4 x64
Kernel 6.1.0-17-amd64
Nothing special 

Thanks for advices

**Comment by unixfox** [comment]
Please post the operating system and version of the operating system.

**Comment by cfdisk** [comment]
Added requested infop to original post. 

It feels like some kind of timeout thing

**Comment by adambala** [comment]
I have the exact same issue except in my situation the script **doesn't work without errors at all**.

`ping6 ipv6.google.com` command gives me these stats:
```
--- ipv6.google.com ping statistics ---
81 packets transmitted, 81 received, 0% packet loss, time 80114ms
rtt min/avg/max/mdev = 0.367/0.554/1.386/0.217 ms
```

I'm trying to run it on the Digital Ocean droplet:
- Linux: Ubuntu 23.10 x64
- Kernel: 6.5.0-14-generic

IPv6 is enabled.

**Comment by unixfox** [comment]
> I have the exact same issue except in my situation the script **doesn't work without errors at all**.
> 
> `ping6 ipv6.google.com` command gives me these stats:
> 
> ```
> --- ipv6.google.com ping statistics ---
> 81 packets transmitted, 81 received, 0% packet loss, time 80114ms
> rtt min/avg/max/mdev = 0.367/0.554/1.386/0.217 ms
> ```
> 
> I'm trying to run it on the Digital Ocean droplet:
> 
>     * Linux: Ubuntu 23.10 x64
> 
>     * Kernel: 6.5.0-14-generic
> 
> 
> IPv6 is enabled.

That's a non-issue, digitalocean only allow 16 IPv6 addresses. You are not going to have enough ipv6 for the rotation: https://docs.digitalocean.com/glossary/subnet/

**Comment by adambala** [comment]
> > I have the exact same issue except in my situation the script **doesn't work without errors at all**.
> > `ping6 ipv6.google.com` command gives me these stats:
> > ```
> > --- ipv6.google.com ping statistics ---
> > 81 packets transmitted, 81 received, 0% packet loss, time 80114ms
> > rtt min/avg/max/mdev = 0.367/0.554/1.386/0.217 ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm trying to run it on the Digital Ocean droplet:
> > ```
> > * Linux: Ubuntu 23.10 x64
> > 
> > * Kernel: 6.5.0-14-generic
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > IPv6 is enabled.
> 
> That's a non-issue, digitalocean only allow 16 IPv6 addresses. You are not going to have enough ipv6 for the rotation: https://docs.digitalocean.com/glossary/subnet/

This is sad. But thanks for the answer anyway!

**Comment by warnerbryce** [comment]
I have the same problem but for the moment i didn't had the chance to have it working. 
VPS on OVH I have /56 subnet on IPv6
Debian 12
Netplan 
i type the command python3 smart-ipv6-rotator.py run --ipv6range=(Network found via gestioip.net)/56

If i change the IPv6 in the Netplan conf with a random one in the same network, it works... but not with this tool.

**Comment by cfdisk** [comment]
As a workaround for *me* I'm running the script in a loop until it returns 0:

```
until ./smart-ipv6-rotator.py run --ipv6range=<mysubnet>::/64
do
    sleep 3
done
```

**Comment by warnerbryce** [comment]
> As a workaround for _me_ I'm running the script in a loop until it returns 0:
> 
> ```
> until ./smart-ipv6-rotator.py run --ipv6range=<mysubnet>::/64
> do
>     sleep 3
> done
> ```

Thanks, in my case it doesn't work. 
The script run for 34 hours and still didn't found a valid IP. 
I will switch manually everytime my service crash, it will be quicker.

**Comment by unixfox** [comment]
Please test with the latest code update. Do a clean before upgrading: https://github.com/iv-org/smart-ipv6-rotator?tab=readme-ov-file#upgrading

**Comment by cfdisk** [comment]
I updated according to instructions.

The problem remains for me, however it has become very rare: on average, it only fails once in about 5 attempts

**Comment by unixfox** [comment]
We now have 3 retries and with a timeout of 10 seconds when testing the IPv6 connectivity.

If you are still running into issues is that:

- you have not configured the correct IPv6 subnet size
- your provider may not allow you to change the IPv6 address too frequently
- your server may have difficulties reaching the test ipv6 server from time to time
