### ISSUE TITLE
can't start ipv6 rotator

### ISSUE THREAD

**Issue by ABCraft19** [iv-org/smart-ipv6-rotator#19]
hello, it's the first time that i use smart ipv6 rotator. I want to start for the first time th py fil but when i start the command i have this error : 

Failed to remove the configured (Google) IPv6 subnets.
        May be expected if the route were not yet configured and that was a cleanup due to an error.
[INFO] Finished cleaning up previous setup.
[INFO] Waiting for the propagation in the Linux kernel.
[ERROR] Failed to send the request for checking the new IPv6 address! The setup did not work!
        Your provider probably does not allow setting any arbitrary IPv6 address.
        Or did you correctly configured the IPv6 subnet to use?
       Exception:
HTTPConnectionPool(host='2606:4700::6812:7261', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70a5dc55ca30>: Failed to establish a new connection: [Errno 113] No route to host'))

My internet provider is Free (french) and I don't know is this information is important

**Comment by unixfox** [comment]
Does your internet provider allow you to assign any ipv6 arbitrary ranges?

**Comment by ABCraft19** [comment]
I don't know, They don't say anything about it

**Comment by ABCraft19** [comment]
I don't know, They don't say anything about it

**Comment by unixfox** [comment]
I'll close this issue because it's most likely free doesn't allow to assign arbitrary IPv6 addresses.
