### ISSUE TITLE
Debian 11 & 12 not working

### ISSUE THREAD

**Issue by PrivacyOsint2** [iv-org/smart-ipv6-rotator#20]
/usr/local/lib/python3.11/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
[INFO] You have IPv6 connectivity. Continuing.
[INFO] No cleanup of previous setup needed.
Traceback (most recent call last):
  File "/root/smart-ipv6-rotator/smart-ipv6-rotator.py", line 310, in <module>
    SmartIPv6Rotator()
  File "/root/smart-ipv6-rotator/smart-ipv6-rotator.py", line 53, in __init__
    getattr(self, args.command)()
  File "/root/smart-ipv6-rotator/smart-ipv6-rotator.py", line 183, in run
    ipv6_network = IPv6Network(args.ipv6range)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 2227, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: myaddress:1/64 has host bits set

**Comment by PrivacyOsint2** [comment]
I have followed the guide:
https://docs.invidious.io/ipv6-rotator/#if-you-are-running-invidious-in-docker

Unable to make this work in Debian 11 & 12.

**Comment by unixfox** [comment]
You need to pass the subnet and not a single ipv6 address.

Please read again the guide.

**Comment by PrivacyOsint2** [comment]
Thank You
