### ISSUE TITLE
Where is the subnet?

### ISSUE THREAD

**Issue by satoshinotdead** [iv-org/smart-ipv6-rotator#23]
I'm following [the guide](https://docs.invidious.io/ipv6-rotator/#configure-the-ipv6-rotator-made-by-invidious-team) and sorry about my ignorance but where is _subnet_ on Subnet Calculator?

I see a lot of links and numbers but no one is specifically tagged like subnet and I'm new on IPV6. So, what's the value of the subnet on the detailed table?

Can anyone show an example of subnet on IPV6, at least?

**Comment by unixfox** [comment]
subnet is called "network" on the tool https://www.gestioip.net/cgi-bin/subnet_calculator.cgi, you will need to add the CIDR too like explained in the guide.

**Comment by satoshinotdead** [comment]
> subnet is called "network" on the tool https://www.gestioip.net/cgi-bin/subnet_calculator.cgi, you will need to add the CIDR too like explained in the guide.

Hello, thanks for your reply. Unfortunately, I don't see any mention of CIDR on the guide.

Perhaps because we are talking about different ones? Please, can you tell me what's the correct input on IP address on the calculator if it's not _IP address_ and needs something more?

A simple example should be greatly appreciated because no everyone knows the same that you already know (:

**Comment by unixfox** [comment]
The CIDR is most likely /64. You can find it using `ip -6 a`
