### ISSUE TITLE
The --services option is useless

### ISSUE THREAD

**Issue by Troughy** [iv-org/smart-ipv6-rotator#26]
The README includes a `--services` option: 
> Define IPV6 ranges of popular services (e.g., --services google, twitter)     

Problem is, twitter's IPv6 ranges are not hardcoded, despite the example. Actually, no service's IPv6 ranges are hardcoded, other than Google's.

**Comment by WardPearce** [comment]
The ``--services`` flag was added to make addressing other services IPV6 ranges in the future easier. Currently it only supports Google, but any developer could open a PR in the future to add another service.

I agree, the documentation should probably accurately reflex the services available.

**Comment by Troughy** [comment]
And how do I get the IPv6 ranges for other services? Do I monitor their DNS records for a long time?

**Comment by WardPearce** [comment]
Depends on the service, some companies publicly list their IPV6 ranges and some you'd have to monitor to find.
