### ISSUE TITLE
IP rotation?

### ISSUE THREAD

**Issue by Elite** [iv-org/smart-ipv6-rotator#28]
I setupped this up and everything worked fine, but all requests for yt-dlp are showing me the same ipv6 address, does this works for invidious only?

```
python3.12 smart-ipv6-rotator.py run --ipv6range=XXXX:XXXX:XXX:2::/64
[INFO] You have IPv6 connectivity. Continuing.
[INFO] No cleanup of previous setup needed.
[DEBUG] Debug info:
ranges --> ['XXXX:XXXX:XXX::/36', 'XXXX:XXXX:XXX::/36', 'XXXX:XXXX:XXX::/36', 'XXXX:XXXX:XXX:/36', 'XXXX:XXXX:XXX:/36', 'XXXX:XXXX:XXX::/36']
random_ipv6_address --> XXXX:XXXX:XXX:2:33c9:910a:5bf:4ffc
gateway --> XXXX:XXXX:XXX:1::11
interface_index --> 2
interface_name --> enp129s0f0
ipv6_subnet --> XXXX:XXXX:XXX:2::/64
random_ipv6_address_mask --> 64
[INFO] Correctly using the new random IPv6 address, continuing.
[INFO] Correctly configured the IPv6 routes for IPv6 ranges ['XXXX:XXXX:XXX::/36', 'XXXX:XXXX:XXX::/36', 'XXXX:XXXX:XXX::/36', 'XXXX:XXXX:XXX:/36', 'XXXX:XXXX:XXX:/36', 'XXXX:XXXX:XXX::/36'].
[INFO] Successful setup. Waiting for the propagation in the Linux kernel.
```

**Comment by Elite** [comment]
@unixfox Any pointres would be greatly appericated.

**Comment by unixfox** [comment]
This works for all the programs using ipv6 connectivity.

**Comment by Elite** [comment]
Hey you forgot to read the question? 

> all requests for yt-dlp are showing me the same ipv6 address

it should use a new ip on every request right?

**Comment by unixfox** [comment]
I said it works on all the programs that use ipv6 connectivity, so it implies that if the mechanism to change the ipv6 address works on invidious then it will work on yt-dlp.

**Comment by Elite** [comment]
Understood, but that is what is not working (or I am doing something wrong). when I try to use the below code in console:
```for i in {1..10}; do curl -6 ifconfig.co; sleep 5; done
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
curl: (7) Failed to connect to ifconfig.co port 80 after 422 ms: No route to host
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
curl: (7) Failed to connect to ifconfig.co port 80 after 421 ms: No route to host
XXXX:XXXX:XXX:2:aae6:4935:6f6e:ed95
```

As you can see the public ip is not changing, using the same command after 5 minutes the results are with same ip.

**Comment by unixfox** [comment]
This script only changes the public address for Google IPv6 subnets. It doesn't affect the main public IPv6 configured.

> How does this script work?

-> https://github.com/iv-org/smart-ipv6-rotator/tree/master?tab=readme-ov-file#how-does-this-script-work

Since `ifconfig.co` is not part of Google ipv6 subnets, the IPv6 address won't change.

But if you want to add more IPv6 subnets, use option `--external-ipv6-ranges`: https://github.com/iv-org/smart-ipv6-rotator/tree/master?tab=readme-ov-file#run-subcommand

**Comment by Elite** [comment]
Oh thanks a lot for the clarification :)

**Comment by unixfox** [comment]
> > This script only changes the public IPv6 address for Google IPv6 subnets. It doesn't affect the main public IPv6 configured.
> > 
> > > How does this script work?
> > 
> > -> https://github.com/iv-org/smart-ipv6-rotator/tree/master?tab=readme-ov-file#how-does-this-script-work
> > 
> > Since `ifconfig.co` is not part of Google ipv6 subnets, the public IPv6 address used won't change.
> > 
> > But if you want to add more IPv6 subnets, use option `--external-ipv6-ranges`: https://github.com/iv-org/smart-ipv6-rotator/tree/master?tab=readme-ov-file#run-subcommand
> 
> Is there a way to add _all_ external ipv6-ranges? I don't want this to be only limited to some services. It should be global/universal. 

Sure use external-ipv6-ranges for all public ipv6 ranges: https://serverfault.com/questions/546606/what-are-the-ipv6-public-and-private-and-reserved-ranges
