### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by mooleshacat** [iv-org/smart-ipv6-rotator#30]
I installed dependencies.

When running command ```python3 smart-ipv6-rotator.py run --ipv6range=2607:f1c0:f066:7900::/64``` I get the following errors:

> Traceback (most recent call last):
>   File "/root/remote-repos/ipv6-rotator-iv-org/smart-ipv6-rotator.py", line 1, in <module>
>     from smart_ipv6_rotator import main
>   File "/root/remote-repos/ipv6-rotator-iv-org/smart_ipv6_rotator/__init__.py", line 21, in <module>
>     from smart_ipv6_rotator.helpers import (
>   File "/root/remote-repos/ipv6-rotator-iv-org/smart_ipv6_rotator/helpers.py", line 44, in <module>
>     services: str | None = None,
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by unixfox** [comment]
Make sure to run a recent version of python.
